server:
  port: 8080

spring:
  datasource:
    dynamic:
      # 设置默认的数据源
      primary: master
      # 严格匹配数据源，默认false
      strict: false
      datasource:
        # 主数据源
        master:
          url: jdbc:postgresql://123.249.23.220:26000/postgres
          driver-class-name: org.postgresql.Driver
          username: student
          password: Bigdata@123

        #  从数据源
        slave_1:
          url: jdbc:postgresql://123.249.23.220:26000/postgres
          driver-class-name: org.postgresql.Driver
          username: teacher
          password: Bigdata@123

        slave_2:
          url: jdbc:postgresql://123.249.23.220:26000/postgres
          driver-class-name: org.postgresql.Driver
          username: admin
          password: Bigdata@123

    druid:
      initial-size: 5     #初始化大小
      min-idle: 10        #最小连接数
      max-active: 20      #最大连接数
      max-wait: 60000     #获取连接时的最大等待时间


